version: "3"
services:
  wordpress:
    image: wordpress:5.6-php7.4
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    container_name: wordpress_app
    ports:
      - 8080:80
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always